#!/usr/bin/python3 -B

import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import utils

CGBC = os.path.join(os.path.dirname(sys.argv[0]), '../target/solvers/cgbc')


def main():
    time, output = utils.subprocess_time_output(
        [CGBC, '0', sys.argv[1], '/dev/null'])
    try:
        os.remove('resumo.txt')
    except:
        pass
    print(float(get_value('T(s): ', output)))
    print(float(get_value('UB: ', output)))
    print("")  # no solution


def get_value(key, output):
    for line in reversed(output):
        if line.startswith(key):
            return line[len(key):].strip()


if __name__ == "__main__":
    main()
