#!/usr/bin/env -S python3 -B

import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import utils

JAR = os.path.join(
    os.path.dirname(sys.argv[0]), '../target/solvers/dcmstp-choco/target/dcmstp-choco-4.1.1-shaded.jar')


def main():
    (time, output) = utils.subprocess_time_output(
        ['java', '-jar', JAR, sys.argv[1]])
    print(float(get_value('time = ', output)))
    print(float(get_value('obj = ', output)))
    print(get_value('solution = ', output))


def get_value(key, output):
    for line in reversed(output):
        if line.startswith(key):
            return line[len(key):].strip()


if __name__ == "__main__":
    main()
