#!/usr/bin/python3 -B

from __future__ import print_function

import os
import subprocess
import sys

import utils

def main():
    if len(sys.argv) < 4:
        usage()
        sys.exit(1)
    solver = sys.argv[1]
    d = sys.argv[2]
    instances = sys.argv[3:]

    if solver not in get_solvers():
        print('Invalid solver:', solver)
        usage()
        sys.exit(1)

    if d != 'file':
        try:
            d = int(d)
            if d < 2:
                raise Exception()
        except:
            print('d must be file or a number >= 2')
            sys.exit(1)

    run(solver, d, instances)


def run(solver, d, instances):
    print('instance,d,solver,time,obj,solution')
    for instance in instances:
        w, dd, s = utils.read(instance)
        if d == 'file':
            if dd == None:
                print(instance, 'no degree constrained provided')
                continue
        else:
            dd = [d] * len(w)
        utils.scale(w, s)
        # TODO: allow run in parallel
        with utils.write_andinst(w, dd) as tmp:
            time, obj, sol = utils.run_solver(solver, instance, tmp.name)
            obj /= s
            print('{},{},{},{:g},{:g},{}'.format(
                instance, d, solver, time, obj, sol))


def usage():
    solvers = get_solvers()
    print(
        'Usage: {} solver (file | number) instance [instance ...]'.format(sys.argv[0]))
    print('    solver - one of', ', '.join(solvers))
    print('    file   - the degree constrain is read from the instance file')
    print('    numer  - use number as degree constraint (>= 2)')


def get_solvers():
    def is_exe(fpath):
        return os.path.isfile(fpath) and os.access(fpath, os.X_OK)
    return sorted(list(s for s in os.listdir('solvers/') if is_exe('solvers/' + s)))


if __name__ == "__main__":
    main()
